### ISSUE TITLE
[PinDMs] Settings lost after each refresh

### ISSUE THREAD

**Issue by KaKi87** [E-boi/cumcord-plugins#2]
Hello,

PinDMs settings are lost after each refresh, as if those weren't persisted.

I can reproduce systematically on multiple devices, whether I create categories in settings first then pin DMs after, or pin DMs first and create categories on the fly.

Thanks

**Comment by E-boi** [comment]
should be fixed now

**Comment by KaKi87** [comment]
Well, it's actually weirder : it only remembers the first channel I pinned, and only displays it as pinned once clicking it.
